on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        mkdir -p ~/.wails
        cp wails.json ~/.wails/
        go run GMake/* build -p
        npm install -g appdmg
        appdmg dmg-spec.json iamgemagick-ui.dmg

    - name: upload artifact macOS
      uses: actions/upload-artifact@v1
      with:
        name: iamgemagick-ui-macOS
        path: iamgemagick-ui.dmg

  release:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: true
      - name: Download macOS package
        uses: actions/download-artifact@v1
        with:
          name: iamgemagick-ui-macOS
      - name: Upload macOS package to release
        id: upload-macOS-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./iamgemagick-ui-macOS/iamgemagick-ui.dmg
          asset_name: magick-app_${{ github.ref }}_macOS.dmg
          asset_content_type: application/octet-stream

